In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [21]:
dataset = pd.read_excel('Data.csv.xlsx')
x = dataset.iloc[[0,1,2,3,4,5,6,7,8,9,10],[0,1,3,4,5,6,7,8,9]]
y = dataset.iloc[[0,1,2,3,4,5,6,7,8,9,10],[2]]

In [19]:
print(x)

    SNo  Name                Date        High         Low        Open  \
0     1  Aave 2020-10-05 23:59:59  5511235847  4978789992  5267503496   
1     2  Aave 2020-10-06 23:59:59  5340227002  4073457791  5329196931   
2     3  Aave 2020-10-07 23:59:59  4240831364  3597068975  4239994711   
3     4  Aave 2020-10-08 23:59:59  4490251114  3669605677  3988526234   
4     5  Aave 2020-10-09 23:59:59  4756953274   432917758  4376446306   
5     6  Aave 2020-10-10 23:59:59   514056548  4670332768  4681814554   
6     7  Aave 2020-10-11 23:59:59  5145337431  4871603954  4913312951   
7     8  Aave 2020-10-12 23:59:59  5442141763  4875407708  4966157329   
8     9  Aave 2020-10-13 23:59:59  5748190422  4959873521  5223839242   
9    10  Aave 2020-10-14 23:59:59  5785394649  4962952942  5137289869   
10   11  Aave 2020-10-15 23:59:59  5208068541  4401832531  5138760962   

         Close        Volume     Marketcap  
0   5321924296  0.000000e+00  8.912813e+15  
1   4240159861  5.830915e+12  7.1

In [22]:
print(y)

   Symbol
0    AAVE
1    AAVE
2    AAVE
3    AAVE
4    AAVE
5    AAVE
6    AAVE
7    AAVE
8    AAVE
9    AAVE
10   AAVE


In [28]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [29]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Aave'
  Timestamp('2020-10-05 23:59:59') 5511235847 4978789992 5267503496
  5321924296 0.0 8912812886084650.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Aave'
  Timestamp('2020-10-06 23:59:59') 5340227002 4073457791 5329196931
  4240159861 5830914597628.0 7101144125451230.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Aave'
  Timestamp('2020-10-07 23:59:59') 4240831364 3597068975 4239994711
  4008397561 68283418632335.0 6713003689981820.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Aave'
  Timestamp('2020-10-08 23:59:59') 4490251114 3669605677 3988526234
  4376446306 165881692260445.0 2.20265142109567e+16]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 'Aave'
  Timestamp('2020-10-09 23:59:59') 4756953274 432917758 4376446306
  4681774415 8155376607835.0 2.35632208162698e+16]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 'Aave'
  Timestamp('2020-10-10 23:59:59') 514056548 4670332768 4681814554
  4913371767 107462702770495.0 2.472

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [27]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0]


In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [33]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 'Aave'
  Timestamp('2020-10-14 23:59:59') 5785394649 4962952942 5137289869
  5131651791 313240542216768.0 2.58274392508111e+16]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Aave'
  Timestamp('2020-10-06 23:59:59') 5340227002 4073457791 5329196931
  4240159861 5830914597628.0 7101144125451230.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 'Aave'
  Timestamp('2020-10-11 23:59:59') 5145337431 4871603954 4913312951
  4966072573 69215060094118.0 2.49940843432422e+16]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Aave'
  Timestamp('2020-10-05 23:59:59') 5511235847 4978789992 5267503496
  5321924296 0.0 8912812886084650.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 'Aave'
  Timestamp('2020-10-12 23:59:59') 5442141763 4875407708 4966157329
  5223869222 135483606481028.0 2.62915666293072e+16]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 'Aave'
  Timestamp('2020-10-15 23:59:59') 5208068541 4401832531 5138760962
  4401918294 588314606280652.0

In [34]:
print(x_test)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Aave'
  Timestamp('2020-10-07 23:59:59') 4240831364 3597068975 4239994711
  4008397561 68283418632335.0 6713003689981820.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Aave'
  Timestamp('2020-10-08 23:59:59') 4490251114 3669605677 3988526234
  4376446306 165881692260445.0 2.20265142109567e+16]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 'Aave'
  Timestamp('2020-10-09 23:59:59') 4756953274 432917758 4376446306
  4681774415 8155376607835.0 2.35632208162698e+16]]


In [35]:
print(y_train)

[0 0 0 0 0 0 0 0]


In [36]:
print(y_test)

[0 0 0]
